---
title: "The State of Lemurs"
author: "by The Zoboomafoos"
output: github_document
---

## Summary

Introduction
  We began the presentation with an introduction slide titled: "The State of Lemurs: An An exploration into 5 lemur species populations at The Duke Lemur Center". I added a photo of one of the lemur enclosures as the background of this slide and spoke a bit about the Duke Lemur Center and it's focus on conservation. The center houses 72 different species of lemurs so as a group we decided on 5 with methods that will be discussed later in this summary. I added pictures of the lemurs to the first few slides to introduce everyone to the lemurs we were going to be discussing. The five were the Coquerel’s Sifaka, the Gray Mouse Lemur, the Slow Loris, the Fat-Tailed Dwarf Lemur, and the Ring Tailed Lemur known throughout the presentation as their shortened taxon codes PCOQ, MMUR, NCOU, CMED, and LCAT, respectively. 

Methods
  The first step we did was cut down the data into a more manageable size. The raw data set includes 27 different lemur species and any graph made was hard to differentiate between each species. To decide which species to use, we created a bar graph that would display the count of observations in the data set for each species. We took the 4 species with the highest count which are LCAT,CMED,MMUR, and PCOQ. These species have the most observations in the data set meaning that we are able to create more accurate visuals. We also used NCOU which would appear an odd choice since when looking at the bar graph, NCOU is on the lower end when it comes to observations. NCOU was chosen to be used in our visuals due to an interesting relationship we found when creating visuals for NCOU. After cutting down the species being visualized to five, we created three visuals to help explore what factors have the greatest impact on lemur populations.

Visual Results

Visual Result 1
  We first wanted to look at how long the different lemur species we living in general. It varied a lot due to the size/weight of the lemurs. The longest living species were LCAT and PCOQ with both living up to 30 years. Next is CMED living up to 20 years, and MMUR living up to 10 years. NCOU only had around 15 to 20 data points for the the age_of_living variable, so even though they all were living around 20 years, it is not significant enough of data to make any strong conclusions. We also chose to color the bars according to sex, however the graphs shows there is not a strong correlation between age of living lemurs and sex. 

Visual Result 2
  We then took a look at litter size since traditionally, a higher litter size correlates with a smaller lifespan since rearing a lot of offspring is an energetically taxing life event in ecology. The litter size also was slightly varied according to weight. The largest litter size was from CMED and MMUR since they had the capacity to have 4 offspring at a time. LCAT would have around 1-2 offspring per litter. NCOU and PCOQ both consistently would only have one child per litter. These graphs also varied a lot in just the amount of data points available for each species but they all had at least 150 observations. 


Visual Result 3
  We wanted to take a look at how the lemurs were aging and how their lifespan is affected by life at the sanctuary and if they are at greater risk of going extinct because of it. So we decided to plot out the Date of Death by Age at Death of the lemurs as well as include a linear fit. CMED, LCAT, NCOU, and PCOQ all show that they are in fact living a lot longer over time. PCOQ does have a lot of infant or near infant deaths compared to the other 3, with LCAT also having an abnormally high amount. MMUR on the other hand is the only species of the 5 we chose that shows they are not living longer during their stay at the sanctuary. They already rarely live to 15 years old as it is, but this is still a startling trend. It could mean that the population at the sanctuary is missing something that they normally have in the wild. Alternatively this species may be dying out regardless of what we do for them.


Conclusion
  Now let’s sum up and discuss conclusion we found. First, lemur populations have been largely grown in captivity due to deforestation and displacement. This was made evident by this sanctuary’s data. We concentrated this data by focusing on 5 key species of lemurs in our data set. We found that lemur lifespans heavily depend on weight, while sex does not play a major determining factor in lifespan. We also observed that a higher litter size usually means a high lifespan as well. And finally, we found that lifespan also depends more heavily on weight than on litter size as smaller lemur species who have a higher litter size will still have a relatively small lifespan.
	These are important finding for the future of these lemur species. While the lemurs discussed here are not all the most endangered species of lemur, the data we recovered from them can be used to protect those species which are.


## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

Zehr, SM, Roach RG, Haring D, Taylor J, Cameron FH, Yoder AD. Life history profiles for 27 strepsirrhine primate taxa generated using captive data from the Duke Lemur Center. Sci. Data 1:140019 doi: 10.1038/sdata.2014.19 (2014).

## References

Lemur data comes from the Duke Lemur Center in Durham County, North Carolina.
